# Generated by Django 4.2.4 on 2023-09-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hibah', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersupportticket',
            old_name='EmployeeId',
            new_name='employeeId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeId',
            new_name='employeeId',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='EmployeeId',
            new_name='employeeId',
        ),
    ]
